name:                pfaatree
version:             0.1.0.0
github:              "tomcumming/pfaatree"
license:             BSD3
author:              "Tom Cumming"
maintainer:          "mail@tomcumming.co.uk"
copyright:           "2019 Tom Cumming"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  pfaatree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pfaatree
    - QuickCheck >= 2.13
    - containers >= 0.6
